version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.10"
    apt_packages:
        - gdal
        - python3-fiona
        - python3-gdal
        - python3-pyproj

python:
    install:
        - requirements: docs/requirements.txt
    system_packages: true

sphinx:
    configuration: docs/conf.py
